### ISSUE TITLE
Make the site background responsive - for phone and tables

### ISSUE THREAD

**Issue by dance2die** [dance2die/dance2die.github.io#1]
Site background doesn't adjust well when viewed on a phone or a tablet.

**Phone in vertical mode**
![image](https://user-images.githubusercontent.com/8465237/31852382-ee33e9ce-b644-11e7-9d0e-92623845e4c3.png)

**Phone in horizontal mode**
![image](https://user-images.githubusercontent.com/8465237/31852387-f9bfe73e-b644-11e7-8d09-663c6c5d7703.png)

**Tablet**
![image](https://user-images.githubusercontent.com/8465237/31852394-15d37ea4-b645-11e7-9ccb-ee35de9346b1.png)

**Comment by lewjuh** [comment]
can i take this?

**Comment by dance2die** [comment]
@lewjuh Thanks. Let me check it out before merging.

**Comment by dance2die** [comment]
Thank you @lewjuh & @Saiteja-Reddy 
I tested both and merged them both.
